name: Auto Commit

on:
  schedule:
    - cron: '0 */2 * * *'  # A cada 2 horas (UTC)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create file with timestamp
        run: echo "Atividade automática gerada em $(date)" > atividade.txt

      - name: Configurar git
        run: |
          git config --global user.name "shashibukay"
          git config --global user.email "zwirtesff@gmail.com"

      - name: Check for changes
        run: |
          git add atividade.txt
          git diff --cached --exit-code || git commit -m "Atividade automática $(date)"

      - name: Push changes
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/shashibukay/klinpy.git
          git push origin main
